version: '3.8'

services:

  db-csv:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - api-network
    volumes:
      - mysql_data:/var/lib/mysql

  spring-csv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-csv
    networks:
      - api-network
    env_file:
      - .env
    volumes:
      - ./file:${SPRING_PATH_SAVE_FILE}

networks:
  api-network:
    driver: bridge

volumes:
  mysql_data:
